/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nathaniel.F (https://sketchfab.com/NathanielLDEutc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-ship-824473fbea704a0bbc95b19101ff15f9
Title: Rocket Ship
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Rocket(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/rocket_ship.glb')
    const { actions } = useAnimations(animations, group)

    // Memainkan animasi jika ada
    useEffect(() => {
        if (animations.length > 0) {
            // Mainkan animasi pertama
            actions[animations[0].name]?.play();
        }
    }, [actions, animations]);

    // Logika animasi posisi Y (floating effect) seperti Astronaut
    const yPosition = useMotionValue(5);
    const ySpring = useSpring(yPosition, { damping: 30 });

    useEffect(() => {
        ySpring.set(-1); // Target posisi Y
    }, [ySpring]);

    useFrame(() => {
        if (group.current) {
            group.current.position.y = ySpring.get();
        }
    });

    return (
        <group
            ref={group}
            {...props}
            dispose={null}
            position={[50, -300, -350]} rotation={[0, 0, 0]}
        >
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model">
                    <group name="c51ca569e8164c7a9693e3f67dc1dff9fbx">
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Cone001">
                                    <mesh
                                        name="Cone001_01_-_Default_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Cone001_01_-_Default_0'].geometry}
                                        material={materials['01_-_Default']}
                                    />
                                    <mesh
                                        name="Cone001_02_-_Default_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Cone001_02_-_Default_0'].geometry}
                                        material={materials['02_-_Default']}
                                    />
                                    <mesh
                                        name="Cone001_03_-_Default_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Cone001_03_-_Default_0'].geometry}
                                        material={materials['03_-_Default']}
                                    />
                                    <mesh
                                        name="Cone001_07_-_Default_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Cone001_07_-_Default_0'].geometry}
                                        material={materials['07_-_Default']}
                                    />
                                    <mesh
                                        name="Cone001_09_-_Default_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Cone001_09_-_Default_0'].geometry}
                                        material={materials['09_-_Default']}
                                    />
                                    <mesh
                                        name="Cone001_08_-_Default_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes['Cone001_08_-_Default_0'].geometry}
                                        material={materials['08_-_Default']}
                                    />
                                </group>
                                <group name="Birth_001" />
                                <group name="Position_Icon_001" />
                                <group name="Speed_001" />
                                <group name="Rotation_001" />
                                <group name="Shape_001" />
                                <group name="Render_001" />
                                <group name="Display_001" />
                                <group name="Event_001" />
                                <group name="Event_002" />
                                <group name="Display_002" />
                                <group name="Spray002" />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/rocket_ship.glb')